#################################################################################################################
################################################# Common Config #################################################
#################################################################################################################
# Paimon Manager Service Port
server:
  port: 10088

spring:
  # Paimon Manager Service Name
  application:
    name: PaimonManager
  profiles:
    active:  dev
  messages:
    basename: i18n/messages
    encoding: UTF-8

  # mvc config
  mvc:
    pathmatch:
      # Path matching strategy, default ant_path_matcher, support ant_path_matcher and path_pattern_parser
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd HH:mm:ss # date format
      time: HH:mm:ss # time format
      date-time: yyyy-MM-dd HH:mm:ss # date-time format

  # json format global configuration
  jackson:
    time-zone: GMT+8 # Time zone, default is GMT+8
    date-format: yyyy-MM-dd HH:mm:ss # Date format, the default is yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapperLocations: classpath*:mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: is_delete
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: ${spring.application.name}
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false